# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TestDeviceGuru' do
#	pod 'DeviceGuru'
    pod 'DeviceGuru', :path => '../'
end

target 'TestDeviceGuruTests' do
#  pod 'DeviceGuru'
    pod 'DeviceGuru', :path => '../'
end

